/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export const projectModel = {
	languages: {
		default: {
			codename: 'default',
			name: 'Default project language',
		},
	},
	contentTypes: {
		action: {
			codename: 'action',
			name: 'Action',
			elements: {
				options: {
					codename: 'options',
					name: 'Options',
				},
				label: {
					codename: 'label',
					name: 'Label',
				},
				icon: {
					codename: 'icon',
					name: 'Icon',
				},
				actions: {
					codename: 'actions',
					name: 'Actions',
				},
				icon_only: {
					codename: 'icon_only',
					name: 'Icon Only',
				},
				navigation_item: {
					codename: 'navigation_item',
					name: 'Navigation Item',
				},
			},
		},
		assessment: {
			codename: 'assessment',
			name: 'Syllabus Assessment',
			elements: {
				pbd_3: {
					codename: 'pbd_3',
					name: 'PBD - 3',
				},
				sba_12: {
					codename: 'sba_12',
					name: 'SBA - 12',
				},
				life_skills: {
					codename: 'life_skills',
					name: 'Life Skills',
				},
				majorwork_supportingtext: {
					codename: 'majorwork_supportingtext',
					name: 'Major Work - Supporting Text',
				},
				majorwork_advice: {
					codename: 'majorwork_advice',
					name: 'Major Work - Advice',
				},
				sba_supportingtext: {
					codename: 'sba_supportingtext',
					name: 'SBA - Supporting Text',
				},
				related_ace_rules: {
					codename: 'related_ace_rules',
					name: 'Related ACE Rules',
				},
				pbd_5: {
					codename: 'pbd_5',
					name: 'PBD - 5',
				},
				examspecs_hscspecification: {
					codename: 'examspecs_hscspecification',
					name: 'Exam Specs - HSC Specification',
				},
				pbd_1: {
					codename: 'pbd_1',
					name: 'PBD - 1',
				},
				sba_11: {
					codename: 'sba_11',
					name: 'SBA - 11',
				},
				introduction: {
					codename: 'introduction',
					name: 'Introduction',
				},
				examspecs_samplematerial: {
					codename: 'examspecs_samplematerial',
					name: 'Exam Specs - Sample Material',
				},
				common_grade_scale: {
					codename: 'common_grade_scale',
					name: 'Common Grade Scale',
				},
				other_information: {
					codename: 'other_information',
					name: 'Other Information',
				},
				examspecs_supportingtext: {
					codename: 'examspecs_supportingtext',
					name: 'Exam Specs - Supporting Text',
				},
				pbd_supporting_text: {
					codename: 'pbd_supporting_text',
					name: 'PBD - Supporting Text',
				},
				course_performance_descriptions: {
					codename: 'course_performance_descriptions',
					name: 'Course Performance Descriptions',
				},
				pbd_6: {
					codename: 'pbd_6',
					name: 'PBD - 6',
				},
				stagesyears__years: {
					codename: 'stagesyears__years',
					name: 'Years',
				},
				pbd_2: {
					codename: 'pbd_2',
					name: 'PBD - 2',
				},
				pbd_4: {
					codename: 'pbd_4',
					name: 'PBD - 4',
				},
				stagesyears__stages: {
					codename: 'stagesyears__stages',
					name: 'Stages',
				},
			},
		},
		author: {
			codename: 'author',
			name: 'Author',
			elements: {
				photo: {
					codename: 'photo',
					name: 'Photo',
				},
				bio: {
					codename: 'bio',
					name: 'Bio',
				},
				first_name: {
					codename: 'first_name',
					name: 'First Name',
				},
				last_name: {
					codename: 'last_name',
					name: 'Last Name',
				},
			},
		},
		base_form_field: {
			codename: 'base_form_field',
			name: 'Base Form Field',
			elements: {
				default_value: {
					codename: 'default_value',
					name: 'Default Value',
				},
				configuration: {
					codename: 'configuration',
					name: 'Configuration',
				},
				name: {
					codename: 'name',
					name: 'Name',
				},
				label: {
					codename: 'label',
					name: 'Label',
				},
				type: {
					codename: 'type',
					name: 'Type',
				},
			},
		},
		code_block: {
			codename: 'code_block',
			name: 'Code block',
			elements: {
				code: {
					codename: 'code',
					name: 'Code',
				},
			},
		},
		contact_section: {
			codename: 'contact_section',
			name: 'Contact Section',
			elements: {
				title: {
					codename: 'title',
					name: 'Title',
				},
				options: {
					codename: 'options',
					name: 'Options',
				},
				form: {
					codename: 'form',
					name: 'Form',
				},
				content: {
					codename: 'content',
					name: 'Content',
				},
				subtitle: {
					codename: 'subtitle',
					name: 'Subtitle',
				},
			},
		},
		content_section: {
			codename: 'content_section',
			name: 'Content Section',
			elements: {
				options: {
					codename: 'options',
					name: 'Options',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
				actions: {
					codename: 'actions',
					name: 'Actions',
				},
				content: {
					codename: 'content',
					name: 'Content',
				},
				image: {
					codename: 'image',
					name: 'Image',
				},
			},
		},
		course: {
			codename: 'course',
			name: 'Course',
			elements: {
				code: {
					codename: 'code',
					name: 'Code',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
			},
		},
		cta_section: {
			codename: 'cta_section',
			name: 'CTA Section',
			elements: {
				title: {
					codename: 'title',
					name: 'Title',
				},
				subtitle: {
					codename: 'subtitle',
					name: 'Subtitle',
				},
				action: {
					codename: 'action',
					name: 'Action',
				},
			},
		},
		external_image: {
			codename: 'external_image',
			name: 'External Image',
			elements: {
				alt: {
					codename: 'alt',
					name: 'Alt',
				},
				url: {
					codename: 'url',
					name: 'Url',
				},
			},
		},
		external_url: {
			codename: 'external_url',
			name: 'External URL',
			elements: {
				url: {
					codename: 'url',
					name: 'URL',
				},
			},
		},
		faq_item: {
			codename: 'faq_item',
			name: 'FAQ Item',
			elements: {
				answer: {
					codename: 'answer',
					name: 'Answer',
				},
				question: {
					codename: 'question',
					name: 'Question',
				},
			},
		},
		faq_section: {
			codename: 'faq_section',
			name: 'FAQ Section',
			elements: {
				options: {
					codename: 'options',
					name: 'Options',
				},
				subtitle: {
					codename: 'subtitle',
					name: 'Subtitle',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
				faq_items: {
					codename: 'faq_items',
					name: 'FAQ Items',
				},
			},
		},
		feature: {
			codename: 'feature',
			name: 'Feature',
			elements: {
				image: {
					codename: 'image',
					name: 'Image',
				},
				actions: {
					codename: 'actions',
					name: 'Actions',
				},
				content: {
					codename: 'content',
					name: 'Content',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
			},
		},
		features_section: {
			codename: 'features_section',
			name: 'Features Section',
			elements: {
				features: {
					codename: 'features',
					name: 'Features',
				},
				options: {
					codename: 'options',
					name: 'Options',
				},
				subtitle: {
					codename: 'subtitle',
					name: 'Subtitle',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
			},
		},
		focus_area: {
			codename: 'focus_area',
			name: 'Focus Area',
			elements: {
				outcomes: {
					codename: 'outcomes',
					name: 'Outcomes',
				},
				access_points: {
					codename: 'access_points',
					name: 'Access Points',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
				syllabustype__type: {
					codename: 'syllabustype__type',
					name: 'Type',
				},
				teaching_advice: {
					codename: 'teaching_advice',
					name: 'Teaching Advice',
				},
				stages: {
					codename: 'stages',
					name: 'Stages',
				},
				focus_area_groups: {
					codename: 'focus_area_groups',
					name: 'Focus Area Groups',
				},
			},
		},
		focus_area_group: {
			codename: 'focus_area_group',
			name: 'Focus Area Group',
			elements: {
				focus_area_items: {
					codename: 'focus_area_items',
					name: 'Focus Area Items',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
			},
		},
		focus_area_item: {
			codename: 'focus_area_item',
			name: 'Focus Area Item',
			elements: {
				examples: {
					codename: 'examples',
					name: 'Examples',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
				nesa_tags__literacy_interacting: {
					codename: 'nesa_tags__literacy_interacting',
					name: 'Literacy Interacting',
				},
				nesa_tags__literacy_listening: {
					codename: 'nesa_tags__literacy_listening',
					name: 'Literacy Listening',
				},
				tags: {
					codename: 'tags',
					name: 'Tags',
				},
			},
		},
		focus_area_tag: {
			codename: 'focus_area_tag',
			name: 'Focus Area Tag',
			elements: {
				title: {
					codename: 'title',
					name: 'Title',
				},
				description: {
					codename: 'description',
					name: 'Description',
				},
			},
		},
		focus_area_tag_category: {
			codename: 'focus_area_tag_category',
			name: 'Focus Area Tag Category',
			elements: {
				title: {
					codename: 'title',
					name: 'Title',
				},
				sub_category: {
					codename: 'sub_category',
					name: 'Sub Category',
				},
				tags: {
					codename: 'tags',
					name: 'Tags',
				},
			},
		},
		form: {
			codename: 'form',
			name: 'Form',
			elements: {
				content: {
					codename: 'content',
					name: 'Content',
				},
				form_id: {
					codename: 'form_id',
					name: 'Form ID',
				},
				form_action: {
					codename: 'form_action',
					name: 'Form Action',
				},
				fields: {
					codename: 'fields',
					name: 'Fields',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
				submit_label: {
					codename: 'submit_label',
					name: 'Submit Label',
				},
			},
		},
		glossary: {
			codename: 'glossary',
			name: 'Glossary',
			elements: {
				syllabuses: {
					codename: 'syllabuses',
					name: 'Related Syllabuses',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
				description: {
					codename: 'description',
					name: 'Description',
				},
			},
		},
		grid: {
			codename: 'grid',
			name: 'Grid',
			elements: {
				gap_vertical: {
					codename: 'gap_vertical',
					name: 'Gap Vertical',
				},
				tiles: {
					codename: 'tiles',
					name: 'Column',
				},
				gap_horizontal: {
					codename: 'gap_horizontal',
					name: 'Gap Horizontal',
				},
			},
		},
		grid_column: {
			codename: 'grid_column',
			name: 'Grid Column',
			elements: {
				column_widths__lg: {
					codename: 'column_widths__lg',
					name: 'lg',
				},
				tile_content: {
					codename: 'tile_content',
					name: 'Content',
				},
				column_widths__md: {
					codename: 'column_widths__md',
					name: 'md',
				},
				column_widths__xs: {
					codename: 'column_widths__xs',
					name: 'xs',
				},
				column_widths__sm: {
					codename: 'column_widths__sm',
					name: 'sm',
				},
			},
		},
		hero_section: {
			codename: 'hero_section',
			name: 'Hero Section',
			elements: {
				actions: {
					codename: 'actions',
					name: 'Actions',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
				content: {
					codename: 'content',
					name: 'Content',
				},
				image: {
					codename: 'image',
					name: 'Image',
				},
			},
		},
		homepage: {
			codename: 'homepage',
			name: 'Homepage',
			elements: {
				header_logo: {
					codename: 'header_logo',
					name: 'Header Logo',
				},
				subpages: {
					codename: 'subpages',
					name: 'Subpages',
				},
				seo__description: {
					codename: 'seo__description',
					name: 'Description',
				},
				seo__options: {
					codename: 'seo__options',
					name: 'Options',
				},
				acknowledgement: {
					codename: 'acknowledgement',
					name: 'Acknowledgement',
				},
				palette: {
					codename: 'palette',
					name: 'Palette',
				},
				label: {
					codename: 'label',
					name: 'Label',
				},
				seo__canonical_url: {
					codename: 'seo__canonical_url',
					name: 'Canonical URL',
				},
				footer_top_top_sections: {
					codename: 'footer_top_top_sections',
					name: 'Footer Top - Top Sections',
				},
				site_prefix: {
					codename: 'site_prefix',
					name: 'Site Prefix',
				},
				content: {
					codename: 'content',
					name: 'Content',
				},
				main_menu: {
					codename: 'main_menu',
					name: 'Main Menu',
				},
				footer_bottom_menu: {
					codename: 'footer_bottom_menu',
					name: 'Footer Bottom Menu',
				},
				seo__keywords: {
					codename: 'seo__keywords',
					name: 'Keywords',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
				seo__title: {
					codename: 'seo__title',
					name: 'Title',
				},
				footer_top_menu_sections: {
					codename: 'footer_top_menu_sections',
					name: 'Footer Top - Menu Sections',
				},
				favicon: {
					codename: 'favicon',
					name: 'Favicon',
				},
			},
		},
		homepage_banner: {
			codename: 'homepage_banner',
			name: 'Homepage Banner',
			elements: {
				title: {
					codename: 'title',
					name: 'Title',
				},
				button_label: {
					codename: 'button_label',
					name: 'Button Label',
				},
			},
		},
		homepage_link_card: {
			codename: 'homepage_link_card',
			name: 'Homepage Link Card',
			elements: {
				title: {
					codename: 'title',
					name: 'Title',
				},
				path: {
					codename: 'path',
					name: 'Path',
				},
			},
		},
		homepage_tile_callout: {
			codename: 'homepage_tile_callout',
			name: 'Homepage Tile Callout',
			elements: {
				divider_color: {
					codename: 'divider_color',
					name: 'Divider Color',
				},
				font_color: {
					codename: 'font_color',
					name: 'Font Color',
				},
				tiles: {
					codename: 'tiles',
					name: 'Tiles',
				},
				arrow_color: {
					codename: 'arrow_color',
					name: 'Arrow Color',
				},
				background_color: {
					codename: 'background_color',
					name: 'Background Color',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
			},
		},
		homepage_tile_callout_tile: {
			codename: 'homepage_tile_callout_tile',
			name: 'Homepage Tile Callout - Tile',
			elements: {
				column_widths__lg: {
					codename: 'column_widths__lg',
					name: 'lg',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
				column_widths__md: {
					codename: 'column_widths__md',
					name: 'md',
				},
				prefix: {
					codename: 'prefix',
					name: 'Prefix',
				},
				column_widths__xs: {
					codename: 'column_widths__xs',
					name: 'xs',
				},
				path: {
					codename: 'path',
					name: 'Path',
				},
				column_widths__sm: {
					codename: 'column_widths__sm',
					name: 'sm',
				},
			},
		},
		icon: {
			codename: 'icon',
			name: 'Icon',
			elements: {
				icon_position: {
					codename: 'icon_position',
					name: 'Icon Position',
				},
				icon: {
					codename: 'icon',
					name: 'Icon',
				},
			},
		},
		key_learning_area: {
			codename: 'key_learning_area',
			name: 'Key Learning Area',
			elements: {
				order: {
					codename: 'order',
					name: 'Sort Order',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
				available: {
					codename: 'available',
					name: 'Available',
				},
			},
		},
		landing_page: {
			codename: 'landing_page',
			name: 'Landing page',
			elements: {
				title: {
					codename: 'title',
					name: 'Title',
				},
				sections: {
					codename: 'sections',
					name: 'Sections',
				},
			},
		},
		link_card: {
			codename: 'link_card',
			name: 'Link Card',
			elements: {
				body: {
					codename: 'body',
					name: 'Body',
				},
				path: {
					codename: 'path',
					name: 'Path',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
				color: {
					codename: 'color',
					name: 'Color',
				},
			},
		},
		link_cards_list_section: {
			codename: 'link_cards_list_section',
			name: 'Link Cards List Section',
			elements: {
				cards: {
					codename: 'cards',
					name: 'Cards',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
			},
		},
		listing_page: {
			codename: 'listing_page',
			name: 'Listing page',
			elements: {
				title: {
					codename: 'title',
					name: 'Title',
				},
				content_type: {
					codename: 'content_type',
					name: 'Content type',
				},
			},
		},
		listing_section: {
			codename: 'listing_section',
			name: 'Listing Section',
			elements: {
				options: {
					codename: 'options',
					name: 'Options',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
				content_type: {
					codename: 'content_type',
					name: 'Content type',
				},
				subtitle: {
					codename: 'subtitle',
					name: 'Subtitle',
				},
				number_of_items: {
					codename: 'number_of_items',
					name: 'Number of items',
				},
				order_by: {
					codename: 'order_by',
					name: 'Order by',
				},
			},
		},
		math_formula: {
			codename: 'math_formula',
			name: 'Math Formula',
			elements: {
				is_block: {
					codename: 'is_block',
					name: 'Is Block?',
				},
				formula: {
					codename: 'formula',
					name: 'Formula',
				},
			},
		},
		menu: {
			codename: 'menu',
			name: 'Menu',
			elements: {
				label: {
					codename: 'label',
					name: 'Label',
				},
				actions: {
					codename: 'actions',
					name: 'Actions',
				},
			},
		},
		navigation_item: {
			codename: 'navigation_item',
			name: 'Navigation Item',
			elements: {
				content: {
					codename: 'content',
					name: 'Content',
				},
				seo__description: {
					codename: 'seo__description',
					name: 'Description',
				},
				seo__options: {
					codename: 'seo__options',
					name: 'Options',
				},
				seo__canonical_url: {
					codename: 'seo__canonical_url',
					name: 'Canonical URL',
				},
				label: {
					codename: 'label',
					name: 'Label',
				},
				seo__keywords: {
					codename: 'seo__keywords',
					name: 'Keywords',
				},
				seo__title: {
					codename: 'seo__title',
					name: 'Title',
				},
				slug: {
					codename: 'slug',
					name: 'Slug',
				},
				subpages: {
					codename: 'subpages',
					name: 'Subpages',
				},
			},
		},
		newsletter_subscribe_box: {
			codename: 'newsletter_subscribe_box',
			name: 'Newsletter Subscribe Box',
			elements: {
				createsend_action: {
					codename: 'createsend_action',
					name: 'CreateSend Action',
				},
				createsend_id: {
					codename: 'createsend_id',
					name: 'CreateSend Id',
				},
				input_label: {
					codename: 'input_label',
					name: 'Input Label',
				},
				button_label: {
					codename: 'button_label',
					name: 'Button Label',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
			},
		},
		outcome: {
			codename: 'outcome',
			name: 'Outcome',
			elements: {
				description: {
					codename: 'description',
					name: 'Description',
				},
				code: {
					codename: 'code',
					name: 'Code',
				},
				relatedlifeskillsoutcomes: {
					codename: 'relatedlifeskillsoutcomes',
					name: 'Related Life Skills Outcomes',
				},
				syllabustype__type: {
					codename: 'syllabustype__type',
					name: 'Type',
				},
				isoverarching: {
					codename: 'isoverarching',
					name: 'Is Overarching',
				},
				stages: {
					codename: 'stages',
					name: 'Stages',
				},
			},
		},
		page_stage: {
			codename: 'page_stage',
			name: 'Page Stage',
			elements: {
				stage: {
					codename: 'stage',
					name: 'Stage',
				},
			},
		},
		page_stage_group: {
			codename: 'page_stage_group',
			name: 'Page Stage Group',
			elements: {
				stage_group: {
					codename: 'stage_group',
					name: 'Stage Group',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
				sections: {
					codename: 'sections',
					name: 'Sections',
				},
			},
		},
		post: {
			codename: 'post',
			name: 'Post',
			elements: {
				publishing_date: {
					codename: 'publishing_date',
					name: 'Publishing Date',
				},
				subtitle: {
					codename: 'subtitle',
					name: 'Subtitle',
				},
				seo__description: {
					codename: 'seo__description',
					name: 'Description',
				},
				seo__options: {
					codename: 'seo__options',
					name: 'Options',
				},
				seo__canonical_url: {
					codename: 'seo__canonical_url',
					name: 'Canonical URL',
				},
				author: {
					codename: 'author',
					name: 'Author',
				},
				excerpt: {
					codename: 'excerpt',
					name: 'Excerpt',
				},
				seo__keywords: {
					codename: 'seo__keywords',
					name: 'Keywords',
				},
				seo__title: {
					codename: 'seo__title',
					name: 'Title',
				},
				image: {
					codename: 'image',
					name: 'Image',
				},
				content: {
					codename: 'content',
					name: 'Content',
				},
				slug: {
					codename: 'slug',
					name: 'Slug',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
			},
		},
		pricing_plan: {
			codename: 'pricing_plan',
			name: 'Pricing Plan',
			elements: {
				options: {
					codename: 'options',
					name: 'Options',
				},
				actions: {
					codename: 'actions',
					name: 'Actions',
				},
				subtitle: {
					codename: 'subtitle',
					name: 'Subtitle',
				},
				price: {
					codename: 'price',
					name: 'Price',
				},
				details: {
					codename: 'details',
					name: 'Details',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
			},
		},
		pricing_section: {
			codename: 'pricing_section',
			name: 'Pricing Section',
			elements: {
				title: {
					codename: 'title',
					name: 'Title',
				},
				pricing_plans: {
					codename: 'pricing_plans',
					name: 'Pricing Plans',
				},
				metadata: {
					codename: 'metadata',
					name: 'Metadata',
				},
				subtitle: {
					codename: 'subtitle',
					name: 'Subtitle',
				},
			},
		},
		quote: {
			codename: 'quote',
			name: 'Quote',
			elements: {
				quote_text: {
					codename: 'quote_text',
					name: 'Quote text',
				},
			},
		},
		review: {
			codename: 'review',
			name: 'Review',
			elements: {
				author: {
					codename: 'author',
					name: 'Author',
				},
				content: {
					codename: 'content',
					name: 'Content',
				},
			},
		},
		reviews_section: {
			codename: 'reviews_section',
			name: 'Reviews Section',
			elements: {
				options: {
					codename: 'options',
					name: 'Options',
				},
				reviews: {
					codename: 'reviews',
					name: 'Reviews',
				},
				subtitle: {
					codename: 'subtitle',
					name: 'Subtitle',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
			},
		},
		select_form_field: {
			codename: 'select_form_field',
			name: 'Select Form Field',
			elements: {
				options: {
					codename: 'options',
					name: 'Options',
				},
				label: {
					codename: 'label',
					name: 'Label',
				},
				configuration: {
					codename: 'configuration',
					name: 'Configuration',
				},
				name: {
					codename: 'name',
					name: 'Name',
				},
				default_value: {
					codename: 'default_value',
					name: 'Default Value',
				},
			},
		},
		select_form_field_option: {
			codename: 'select_form_field_option',
			name: 'Select Form Field Option',
			elements: {
				label: {
					codename: 'label',
					name: 'Label',
				},
				value: {
					codename: 'value',
					name: 'Value',
				},
			},
		},
		sharedcontent_richtext: {
			codename: 'sharedcontent_richtext',
			name: 'Shared Content Rich Text',
			elements: {
				content: {
					codename: 'content',
					name: 'Content',
				},
			},
		},
		simple_page: {
			codename: 'simple_page',
			name: 'Simple page',
			elements: {
				subtitle: {
					codename: 'subtitle',
					name: 'Subtitle',
				},
				image: {
					codename: 'image',
					name: 'Image',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
				content: {
					codename: 'content',
					name: 'Content',
				},
			},
		},
		stage: {
			codename: 'stage',
			name: 'Stage',
			elements: {
				order: {
					codename: 'order',
					name: 'Sort Order',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
				years: {
					codename: 'years',
					name: 'Years',
				},
			},
		},
		stage_group: {
			codename: 'stage_group',
			name: 'Stage Group',
			elements: {
				title: {
					codename: 'title',
					name: 'Title',
				},
				order: {
					codename: 'order',
					name: 'Order',
				},
				years: {
					codename: 'years',
					name: 'Years',
				},
				stages: {
					codename: 'stages',
					name: 'Stages',
				},
			},
		},
		syllabus: {
			codename: 'syllabus',
			name: 'Syllabus',
			elements: {
				courseoverview_organisationofcontent: {
					codename: 'courseoverview_organisationofcontent',
					name: 'Course Overview - Organisation Of Content',
				},
				courseoverview_coursenumbers: {
					codename: 'courseoverview_coursenumbers',
					name: 'Course Overview - Course Numbers',
				},
				available: {
					codename: 'available',
					name: 'Available',
				},
				courseoverview_learning1_10: {
					codename: 'courseoverview_learning1_10',
					name: 'Course Overview - Learning 1-10',
				},
				key_learning_area: {
					codename: 'key_learning_area',
					name: 'Key Learning Area',
				},
				overview: {
					codename: 'overview',
					name: 'Course Overview - Introduction',
				},
				from_date: {
					codename: 'from_date',
					name: 'From Date',
				},
				aim: {
					codename: 'aim',
					name: 'Aim',
				},
				courseoverview_achievementhsc: {
					codename: 'courseoverview_achievementhsc',
					name: 'Course Overview - Achievement HSC',
				},
				courseoverview_prerequisits: {
					codename: 'courseoverview_prerequisits',
					name: 'Course Overview - Prerequisites',
				},
				rationale: {
					codename: 'rationale',
					name: 'Rationale',
				},
				assessments: {
					codename: 'assessments',
					name: 'Assessments',
				},
				courseoverview_learning11: {
					codename: 'courseoverview_learning11',
					name: 'Course Overview - Learning 11',
				},
				courseoverview_syllabustype: {
					codename: 'courseoverview_syllabustype',
					name: 'Course Overview - Syllabus Type',
				},
				related_life_skills_syllabus: {
					codename: 'related_life_skills_syllabus',
					name: 'Related Life Skills Syllabus',
				},
				courseoverview_learning12: {
					codename: 'courseoverview_learning12',
					name: 'Course Overview - Learning 12',
				},
				courseoverview_selftuition: {
					codename: 'courseoverview_selftuition',
					name: 'Course Overview - Self Tuition',
				},
				courseoverview_200hourrules: {
					codename: 'courseoverview_200hourrules',
					name: 'Course Overview - 200 Hour Rules',
				},
				outcomes: {
					codename: 'outcomes',
					name: 'Outcomes',
				},
				code: {
					codename: 'code',
					name: 'Code',
				},
				courseoverview_endorsementtype: {
					codename: 'courseoverview_endorsementtype',
					name: 'Course Overview - Endorsement Type',
				},
				courseoverview_exclusions: {
					codename: 'courseoverview_exclusions',
					name: 'Course Overview - Exclusions',
				},
				courseoverview_achievementstage4_5: {
					codename: 'courseoverview_achievementstage4_5',
					name: 'Course Overview - Achievement Stage 4-5',
				},
				courseoverview_enrolmenttype: {
					codename: 'courseoverview_enrolmenttype',
					name: 'Course Overview - Enrolment Type',
				},
				to_date: {
					codename: 'to_date',
					name: 'To Date',
				},
				title: {
					codename: 'title',
					name: 'Title',
				},
				stagesyears__years: {
					codename: 'stagesyears__years',
					name: 'Years',
				},
				courseoverview_eligibility: {
					codename: 'courseoverview_eligibility',
					name: 'Course Overview - Eligibility',
				},
				courseoverview_corequisites: {
					codename: 'courseoverview_corequisites',
					name: 'Course Overview - Corequisites',
				},
				courseoverview_100hourrules: {
					codename: 'courseoverview_100hourrules',
					name: 'Course Overview - 100 Hour Rules',
				},
				courseoverview_courcerequirements: {
					codename: 'courseoverview_courcerequirements',
					name: 'Course Overview - Cource Requirements',
				},
				courseoverview_otherinfo: {
					codename: 'courseoverview_otherinfo',
					name: 'Course Overview - Other Info',
				},
				focus_areas: {
					codename: 'focus_areas',
					name: 'Focus Areas',
				},
				stagesyears__stages: {
					codename: 'stagesyears__stages',
					name: 'Stages',
				},
			},
		},
		teaching_advice: {
			codename: 'teaching_advice',
			name: 'Teaching Advice',
			elements: {
				content: {
					codename: 'content',
					name: 'Content',
				},
			},
		},
	},
	taxonomies: {
		bands: {
			codename: 'bands',
			name: 'Bands',
			terms: {
				n1: {
					codename: 'n1',
					name: '1',
					terms: {},
				},
			},
		},
		interacting: {
			codename: 'interacting',
			name: 'Literacy Interacting',
			terms: {
				eci1a: {
					codename: 'eci1a',
					name: 'ECI1a',
					terms: {},
				},
				eci1b: {
					codename: 'eci1b',
					name: 'ECI1b',
					terms: {},
				},
				int1: {
					codename: 'int1',
					name: 'InT1',
					terms: {},
				},
				int2: {
					codename: 'int2',
					name: 'InT2',
					terms: {},
				},
				int3: {
					codename: 'int3',
					name: 'InT3',
					terms: {},
				},
				int4: {
					codename: 'int4',
					name: 'InT4',
					terms: {},
				},
				int5: {
					codename: 'int5',
					name: 'InT5',
					terms: {},
				},
				int6: {
					codename: 'int6',
					name: 'InT6',
					terms: {},
				},
				int7: {
					codename: 'int7',
					name: 'InT7',
					terms: {},
				},
			},
		},
		listening: {
			codename: 'listening',
			name: 'Literacy Listening',
			terms: {
				ecl1a: {
					codename: 'ecl1a',
					name: 'ECL1a',
					terms: {},
				},
				ecl1b: {
					codename: 'ecl1b',
					name: 'ECL1b',
					terms: {},
				},
				lis1: {
					codename: 'lis1',
					name: 'LiS1',
					terms: {},
				},
				lis2: {
					codename: 'lis2',
					name: 'LiS2',
					terms: {},
				},
				lis3: {
					codename: 'lis3',
					name: 'LiS3',
					terms: {},
				},
				lis4: {
					codename: 'lis4',
					name: 'LiS4',
					terms: {},
				},
				lis5: {
					codename: 'lis5',
					name: 'LiS5',
					terms: {},
				},
				lis6: {
					codename: 'lis6',
					name: 'LiS6',
					terms: {},
				},
				lis7: {
					codename: 'lis7',
					name: 'LiS7',
					terms: {},
				},
				lis8: {
					codename: 'lis8',
					name: 'LiS8',
					terms: {},
				},
			},
		},
	},
}
