/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export const projectModel = {
  languages: {
    default: {
      codename: 'default',
      name: 'Default project language',
    },
  },
  contentTypes: {
    action: {
      codename: 'action',
      name: 'Action',
      elements: {
        options: {
          codename: 'options',
          name: 'Options',
        },
        label: {
          codename: 'label',
          name: 'Label',
        },
        icon: {
          codename: 'icon',
          name: 'Icon',
        },
        actions: {
          codename: 'actions',
          name: 'Actions',
        },
        role: {
          codename: 'role',
          name: 'Role',
        },
        navigation_item: {
          codename: 'navigation_item',
          name: 'Navigation Item',
        },
      },
    },
    assessment: {
      codename: 'assessment',
      name: 'Assessment',
      elements: {
        years: {
          codename: 'years',
          name: 'Years',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
      },
    },
    author: {
      codename: 'author',
      name: 'Author',
      elements: {
        photo: {
          codename: 'photo',
          name: 'Photo',
        },
        bio: {
          codename: 'bio',
          name: 'Bio',
        },
        first_name: {
          codename: 'first_name',
          name: 'First Name',
        },
        last_name: {
          codename: 'last_name',
          name: 'Last Name',
        },
      },
    },
    base_form_field: {
      codename: 'base_form_field',
      name: 'Base Form Field',
      elements: {
        default_value: {
          codename: 'default_value',
          name: 'Default Value',
        },
        configuration: {
          codename: 'configuration',
          name: 'Configuration',
        },
        name: {
          codename: 'name',
          name: 'Name',
        },
        label: {
          codename: 'label',
          name: 'Label',
        },
        type: {
          codename: 'type',
          name: 'Type',
        },
      },
    },
    code_block: {
      codename: 'code_block',
      name: 'Code block',
      elements: {
        code: {
          codename: 'code',
          name: 'Code',
        },
      },
    },
    contact_section: {
      codename: 'contact_section',
      name: 'Contact Section',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        options: {
          codename: 'options',
          name: 'Options',
        },
        form: {
          codename: 'form',
          name: 'Form',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
        subtitle: {
          codename: 'subtitle',
          name: 'Subtitle',
        },
      },
    },
    content_section: {
      codename: 'content_section',
      name: 'Content Section',
      elements: {
        options: {
          codename: 'options',
          name: 'Options',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        actions: {
          codename: 'actions',
          name: 'Actions',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
      },
    },
    cta_section: {
      codename: 'cta_section',
      name: 'CTA Section',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        subtitle: {
          codename: 'subtitle',
          name: 'Subtitle',
        },
        action: {
          codename: 'action',
          name: 'Action',
        },
      },
    },
    external_url: {
      codename: 'external_url',
      name: 'External URL',
      elements: {
        url: {
          codename: 'url',
          name: 'URL',
        },
      },
    },
    faq_item: {
      codename: 'faq_item',
      name: 'FAQ Item',
      elements: {
        answer: {
          codename: 'answer',
          name: 'Answer',
        },
        question: {
          codename: 'question',
          name: 'Question',
        },
      },
    },
    faq_section: {
      codename: 'faq_section',
      name: 'FAQ Section',
      elements: {
        options: {
          codename: 'options',
          name: 'Options',
        },
        subtitle: {
          codename: 'subtitle',
          name: 'Subtitle',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        faq_items: {
          codename: 'faq_items',
          name: 'FAQ Items',
        },
      },
    },
    feature: {
      codename: 'feature',
      name: 'Feature',
      elements: {
        image: {
          codename: 'image',
          name: 'Image',
        },
        actions: {
          codename: 'actions',
          name: 'Actions',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
    features_section: {
      codename: 'features_section',
      name: 'Features Section',
      elements: {
        features: {
          codename: 'features',
          name: 'Features',
        },
        options: {
          codename: 'options',
          name: 'Options',
        },
        subtitle: {
          codename: 'subtitle',
          name: 'Subtitle',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
    focus_area: {
      codename: 'focus_area',
      name: 'Focus Area',
      elements: {
        outcomes: {
          codename: 'outcomes',
          name: 'Outcomes',
        },
        access_points: {
          codename: 'access_points',
          name: 'Access Points',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        teaching_advice: {
          codename: 'teaching_advice',
          name: 'Teaching Advice',
        },
        focus_area_groups: {
          codename: 'focus_area_groups',
          name: 'Focus Area Groups',
        },
      },
    },
    focus_area_group: {
      codename: 'focus_area_group',
      name: 'Focus Area Group',
      elements: {
        focus_area_items: {
          codename: 'focus_area_items',
          name: 'Focus Area Items',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
    focus_area_item: {
      codename: 'focus_area_item',
      name: 'Focus Area Item',
      elements: {
        examples: {
          codename: 'examples',
          name: 'Examples',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        nesa_tags__literacy_interacting: {
          codename: 'nesa_tags__literacy_interacting',
          name: 'Literacy Interacting',
        },
        nesa_tags__literacy_listening: {
          codename: 'nesa_tags__literacy_listening',
          name: 'Literacy Listening',
        },
      },
    },
    form: {
      codename: 'form',
      name: 'Form',
      elements: {
        content: {
          codename: 'content',
          name: 'Content',
        },
        form_id: {
          codename: 'form_id',
          name: 'Form ID',
        },
        form_action: {
          codename: 'form_action',
          name: 'Form Action',
        },
        fields: {
          codename: 'fields',
          name: 'Fields',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        submit_label: {
          codename: 'submit_label',
          name: 'Submit Label',
        },
      },
    },
    glossary: {
      codename: 'glossary',
      name: 'Glossary',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        description: {
          codename: 'description',
          name: 'Description',
        },
        key_learning_area: {
          codename: 'key_learning_area',
          name: 'Key Learning Area',
        },
      },
    },
    hero_section: {
      codename: 'hero_section',
      name: 'Hero Section',
      elements: {
        actions: {
          codename: 'actions',
          name: 'Actions',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
      },
    },
    homepage: {
      codename: 'homepage',
      name: 'Homepage',
      elements: {
        header_logo: {
          codename: 'header_logo',
          name: 'Header Logo',
        },
        font: {
          codename: 'font',
          name: 'Font',
        },
        subpages: {
          codename: 'subpages',
          name: 'Subpages',
        },
        seo__description: {
          codename: 'seo__description',
          name: 'Description',
        },
        seo__options: {
          codename: 'seo__options',
          name: 'Options',
        },
        palette: {
          codename: 'palette',
          name: 'Palette',
        },
        label: {
          codename: 'label',
          name: 'Label',
        },
        seo__canonical_url: {
          codename: 'seo__canonical_url',
          name: 'Canonical URL',
        },
        site_prefix: {
          codename: 'site_prefix',
          name: 'Site Prefix',
        },
        copyright: {
          codename: 'copyright',
          name: 'Copyright',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
        main_menu: {
          codename: 'main_menu',
          name: 'Main Menu',
        },
        seo__keywords: {
          codename: 'seo__keywords',
          name: 'Keywords',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        seo__title: {
          codename: 'seo__title',
          name: 'Title',
        },
        footer_sections: {
          codename: 'footer_sections',
          name: 'Footer sections',
        },
        favicon: {
          codename: 'favicon',
          name: 'Favicon',
        },
      },
    },
    icon: {
      codename: 'icon',
      name: 'Icon',
      elements: {
        icon_position: {
          codename: 'icon_position',
          name: 'Icon Position',
        },
        icon: {
          codename: 'icon',
          name: 'Icon',
        },
      },
    },
    key_learning_area: {
      codename: 'key_learning_area',
      name: 'Key Learning Area',
      elements: {
        order: {
          codename: 'order',
          name: 'Order',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        available: {
          codename: 'available',
          name: 'Available',
        },
      },
    },
    landing_page: {
      codename: 'landing_page',
      name: 'Landing page',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        sections: {
          codename: 'sections',
          name: 'Sections',
        },
      },
    },
    listing_page: {
      codename: 'listing_page',
      name: 'Listing page',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        content_type: {
          codename: 'content_type',
          name: 'Content type',
        },
      },
    },
    listing_section: {
      codename: 'listing_section',
      name: 'Listing Section',
      elements: {
        options: {
          codename: 'options',
          name: 'Options',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        content_type: {
          codename: 'content_type',
          name: 'Content type',
        },
        subtitle: {
          codename: 'subtitle',
          name: 'Subtitle',
        },
        number_of_items: {
          codename: 'number_of_items',
          name: 'Number of items',
        },
        order_by: {
          codename: 'order_by',
          name: 'Order by',
        },
      },
    },
    menu: {
      codename: 'menu',
      name: 'Menu',
      elements: {
        label: {
          codename: 'label',
          name: 'Label',
        },
        actions: {
          codename: 'actions',
          name: 'Actions',
        },
      },
    },
    navigation_item: {
      codename: 'navigation_item',
      name: 'Navigation Item',
      elements: {
        content: {
          codename: 'content',
          name: 'Content',
        },
        seo__description: {
          codename: 'seo__description',
          name: 'Description',
        },
        seo__options: {
          codename: 'seo__options',
          name: 'Options',
        },
        seo__canonical_url: {
          codename: 'seo__canonical_url',
          name: 'Canonical URL',
        },
        label: {
          codename: 'label',
          name: 'Label',
        },
        seo__keywords: {
          codename: 'seo__keywords',
          name: 'Keywords',
        },
        seo__title: {
          codename: 'seo__title',
          name: 'Title',
        },
        slug: {
          codename: 'slug',
          name: 'Slug',
        },
        subpages: {
          codename: 'subpages',
          name: 'Subpages',
        },
      },
    },
    outcome: {
      codename: 'outcome',
      name: 'Outcome',
      elements: {
        description: {
          codename: 'description',
          name: 'Description',
        },
        code: {
          codename: 'code',
          name: 'Code',
        },
        stages: {
          codename: 'stages',
          name: 'Stages',
        },
      },
    },
    page_stage: {
      codename: 'page_stage',
      name: 'Page Stage',
      elements: {
        stage: {
          codename: 'stage',
          name: 'Stage',
        },
      },
    },
    post: {
      codename: 'post',
      name: 'Post',
      elements: {
        publishing_date: {
          codename: 'publishing_date',
          name: 'Publishing Date',
        },
        subtitle: {
          codename: 'subtitle',
          name: 'Subtitle',
        },
        seo__description: {
          codename: 'seo__description',
          name: 'Description',
        },
        seo__options: {
          codename: 'seo__options',
          name: 'Options',
        },
        seo__canonical_url: {
          codename: 'seo__canonical_url',
          name: 'Canonical URL',
        },
        author: {
          codename: 'author',
          name: 'Author',
        },
        excerpt: {
          codename: 'excerpt',
          name: 'Excerpt',
        },
        seo__keywords: {
          codename: 'seo__keywords',
          name: 'Keywords',
        },
        seo__title: {
          codename: 'seo__title',
          name: 'Title',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
        slug: {
          codename: 'slug',
          name: 'Slug',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
    pricing_plan: {
      codename: 'pricing_plan',
      name: 'Pricing Plan',
      elements: {
        options: {
          codename: 'options',
          name: 'Options',
        },
        actions: {
          codename: 'actions',
          name: 'Actions',
        },
        subtitle: {
          codename: 'subtitle',
          name: 'Subtitle',
        },
        price: {
          codename: 'price',
          name: 'Price',
        },
        details: {
          codename: 'details',
          name: 'Details',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
    pricing_section: {
      codename: 'pricing_section',
      name: 'Pricing Section',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        pricing_plans: {
          codename: 'pricing_plans',
          name: 'Pricing Plans',
        },
        metadata: {
          codename: 'metadata',
          name: 'Metadata',
        },
        subtitle: {
          codename: 'subtitle',
          name: 'Subtitle',
        },
      },
    },
    quote: {
      codename: 'quote',
      name: 'Quote',
      elements: {
        quote_text: {
          codename: 'quote_text',
          name: 'Quote text',
        },
      },
    },
    review: {
      codename: 'review',
      name: 'Review',
      elements: {
        author: {
          codename: 'author',
          name: 'Author',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
      },
    },
    reviews_section: {
      codename: 'reviews_section',
      name: 'Reviews Section',
      elements: {
        options: {
          codename: 'options',
          name: 'Options',
        },
        reviews: {
          codename: 'reviews',
          name: 'Reviews',
        },
        subtitle: {
          codename: 'subtitle',
          name: 'Subtitle',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
    select_form_field: {
      codename: 'select_form_field',
      name: 'Select Form Field',
      elements: {
        options: {
          codename: 'options',
          name: 'Options',
        },
        label: {
          codename: 'label',
          name: 'Label',
        },
        configuration: {
          codename: 'configuration',
          name: 'Configuration',
        },
        name: {
          codename: 'name',
          name: 'Name',
        },
        default_value: {
          codename: 'default_value',
          name: 'Default Value',
        },
      },
    },
    select_form_field_option: {
      codename: 'select_form_field_option',
      name: 'Select Form Field Option',
      elements: {
        label: {
          codename: 'label',
          name: 'Label',
        },
        value: {
          codename: 'value',
          name: 'Value',
        },
      },
    },
    simple_page: {
      codename: 'simple_page',
      name: 'Simple page',
      elements: {
        subtitle: {
          codename: 'subtitle',
          name: 'Subtitle',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
      },
    },
    stage: {
      codename: 'stage',
      name: 'Stage',
      elements: {
        order: {
          codename: 'order',
          name: 'Order',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        available: {
          codename: 'available',
          name: 'Available',
        },
        tag: {
          codename: 'tag',
          name: 'Tag',
        },
      },
    },
    stage_category: {
      codename: 'stage_category',
      name: 'Stage Category',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        stages: {
          codename: 'stages',
          name: 'Stages',
        },
      },
    },
    syllabus: {
      codename: 'syllabus',
      name: 'Syllabus',
      elements: {
        available: {
          codename: 'available',
          name: 'Available',
        },
        key_learning_area: {
          codename: 'key_learning_area',
          name: 'Key Learning Area',
        },
        assessments: {
          codename: 'assessments',
          name: 'Assessments',
        },
        aim: {
          codename: 'aim',
          name: 'Aim',
        },
        overview: {
          codename: 'overview',
          name: 'Overview',
        },
        code: {
          codename: 'code',
          name: 'Code',
        },
        stages: {
          codename: 'stages',
          name: 'Stages',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        rich_text: {
          codename: 'rich_text',
          name: 'Rich text',
        },
        rationale: {
          codename: 'rationale',
          name: 'Rationale',
        },
        focus_areas: {
          codename: 'focus_areas',
          name: 'Focus Areas',
        },
      },
    },
    teaching_advice: {
      codename: 'teaching_advice',
      name: 'Teaching Advice',
      elements: {
        content: {
          codename: 'content',
          name: 'Content',
        },
      },
    },
  },
  taxonomies: {
    interacting: {
      codename: 'interacting',
      name: 'Literacy Interacting',
      terms: {
        eci1a: {
          codename: 'eci1a',
          name: 'ECI1a',
          terms: {},
        },
        eci1b: {
          codename: 'eci1b',
          name: 'ECI1b',
          terms: {},
        },
        int1: {
          codename: 'int1',
          name: 'InT1',
          terms: {},
        },
        int2: {
          codename: 'int2',
          name: 'InT2',
          terms: {},
        },
        int3: {
          codename: 'int3',
          name: 'InT3',
          terms: {},
        },
        int4: {
          codename: 'int4',
          name: 'InT4',
          terms: {},
        },
        int5: {
          codename: 'int5',
          name: 'InT5',
          terms: {},
        },
        int6: {
          codename: 'int6',
          name: 'InT6',
          terms: {},
        },
        int7: {
          codename: 'int7',
          name: 'InT7',
          terms: {},
        },
      },
    },
    listening: {
      codename: 'listening',
      name: 'Literacy Listening',
      terms: {
        ecl1a: {
          codename: 'ecl1a',
          name: 'ECL1a',
          terms: {},
        },
        ecl1b: {
          codename: 'ecl1b',
          name: 'ECL1b',
          terms: {},
        },
        lis1: {
          codename: 'lis1',
          name: 'LiS1',
          terms: {},
        },
        lis2: {
          codename: 'lis2',
          name: 'LiS2',
          terms: {},
        },
        lis3: {
          codename: 'lis3',
          name: 'LiS3',
          terms: {},
        },
        lis4: {
          codename: 'lis4',
          name: 'LiS4',
          terms: {},
        },
        lis5: {
          codename: 'lis5',
          name: 'LiS5',
          terms: {},
        },
        lis6: {
          codename: 'lis6',
          name: 'LiS6',
          terms: {},
        },
        lis7: {
          codename: 'lis7',
          name: 'LiS7',
          terms: {},
        },
        lis8: {
          codename: 'lis8',
          name: 'LiS8',
          terms: {},
        },
      },
    },
  },
};
