import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Accesscontentitem = IContentItem<{
	_syllabus: Elements.TaxonomyElement
	stages__stage_years: Elements.TaxonomyElement
	title: Elements.TextElement
	learningprogression_tags__literacy: Elements.TaxonomyElement
	learningprogression_tags__numeracy: Elements.TaxonomyElement
	stages__stages: Elements.TaxonomyElement
	stages__stage_groups: Elements.TaxonomyElement
	examples: Elements.RichTextElement
	including_statements: Elements.RichTextElement
}>
