import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Assessment = IContentItem<{
  years: Elements.MultipleChoiceElement;
  content: Elements.CustomElement;
}>;
