import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Assessment = IContentItem<{
	introduction: Elements.RichTextElement
	common_grade_scale: Elements.RichTextElement
	course_performance_descriptions: Elements.RichTextElement
	life_skills: Elements.RichTextElement
	other_information: Elements.RichTextElement
	related_ace_rules: Elements.RichTextElement
	pbd_supportingtext: Elements.LinkedItemsElement<IContentItem>
	pbd_6: Elements.RichTextElement
	pbd_5: Elements.RichTextElement
	pbd_4: Elements.RichTextElement
	pbd_3: Elements.RichTextElement
	pbd_2: Elements.RichTextElement
	performance_band_descriptors__pbd__1: Elements.LinkedItemsElement<IContentItem>
	examspec_supportingtext: Elements.LinkedItemsElement<IContentItem>
	examspec_hscspecification: Elements.RichTextElement
	examspec_samplematerial: Elements.RichTextElement
	majorwork_supportingtext: Elements.LinkedItemsElement<IContentItem>
	majorwork_advice: Elements.RichTextElement
	sba_supportingtext: Elements.LinkedItemsElement<IContentItem>
	sba_11: Elements.RichTextElement
	sba_12: Elements.RichTextElement
	assessment_requirements_supportingtext: Elements.LinkedItemsElement<IContentItem>
	assessment_requirements: Elements.RichTextElement
	hsc_supportingtext: Elements.LinkedItemsElement<IContentItem>
	hsc_examinations: Elements.RichTextElement
	stages__stage_groups: Elements.TaxonomyElement
	stages__stages: Elements.TaxonomyElement
	stages__stage_years: Elements.TaxonomyElement
	_syllabus: Elements.TaxonomyElement
}>
