import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Assessment = IContentItem<{
  pbd_3: Elements.RichTextElement;
  sba_12: Elements.RichTextElement;
  life_skills: Elements.RichTextElement;
  majorwork_supportingtext: Elements.LinkedItemsElement<IContentItem>;
  majorwork_advice: Elements.RichTextElement;
  sba_supportingtext: Elements.LinkedItemsElement<IContentItem>;
  related_ace_rules: Elements.RichTextElement;
  pbd_5: Elements.RichTextElement;
  examspecs_hscspecification: Elements.RichTextElement;
  pbd_1: Elements.RichTextElement;
  sba_11: Elements.RichTextElement;
  introduction: Elements.RichTextElement;
  examspecs_samplematerial: Elements.RichTextElement;
  common_grade_scale: Elements.RichTextElement;
  other_information: Elements.RichTextElement;
  examspecs_supportingtext: Elements.LinkedItemsElement<IContentItem>;
  pbd_supporting_text: Elements.LinkedItemsElement<IContentItem>;
  course_performance_descriptions: Elements.RichTextElement;
  pbd_6: Elements.RichTextElement;
  stagesyears__years: Elements.MultipleChoiceElement;
  pbd_2: Elements.RichTextElement;
  pbd_4: Elements.RichTextElement;
  stagesyears__stages: Elements.LinkedItemsElement<IContentItem>;
}>;
