import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Author = IContentItem<{
  photo: Elements.AssetsElement;
  bio: Elements.TextElement;
  first_name: Elements.TextElement;
  last_name: Elements.TextElement;
}>;
