import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type BaseFormField = IContentItem<{
  default_value: Elements.TextElement;
  configuration: Elements.MultipleChoiceElement;
  name: Elements.TextElement;
  label: Elements.TextElement;
  type: Elements.MultipleChoiceElement;
}>;
