import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type ContentSection = IContentItem<{
  options: Elements.MultipleChoiceElement;
  title: Elements.TextElement;
  actions: Elements.LinkedItemsElement<IContentItem>;
  content: Elements.RichTextElement;
  image: Elements.AssetsElement;
}>;
