import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type ContactSection = IContentItem<{
  title: Elements.TextElement;
  options: Elements.MultipleChoiceElement;
  form: Elements.LinkedItemsElement<IContentItem>;
  content: Elements.RichTextElement;
  subtitle: Elements.RichTextElement;
}>;
