import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Contentblock = IContentItem<{
	content: Elements.RichTextElement
	title: Elements.TextElement
	image: Elements.AssetsElement
	more_info_link: Elements.LinkedItemsElement<IContentItem>
	sub_title: Elements.TextElement
}>
