import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Course = IContentItem<{
  code: Elements.TextElement;
  title: Elements.TextElement;
}>;
