import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type FaqSection = IContentItem<{
  options: Elements.MultipleChoiceElement;
  subtitle: Elements.RichTextElement;
  title: Elements.TextElement;
  faq_items: Elements.LinkedItemsElement<IContentItem>;
}>;
