import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type FeaturesSection = IContentItem<{
  features: Elements.LinkedItemsElement<IContentItem>;
  options: Elements.MultipleChoiceElement;
  subtitle: Elements.RichTextElement;
  title: Elements.TextElement;
}>;
