import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Focusarea = IContentItem<{
	syllabus_type__items: Elements.TaxonomyElement
	stages__stage_years: Elements.TaxonomyElement
	outcomes: Elements.LinkedItemsElement<IContentItem>
	continuumgroups: Elements.LinkedItemsElement<IContentItem>
	resources: Elements.AssetsElement
	stages__stages: Elements.TaxonomyElement
	stages__stage_groups: Elements.TaxonomyElement
	addressedinparallel: Elements.LinkedItemsElement<IContentItem>
	accesspointgroups: Elements.LinkedItemsElement<IContentItem>
	syllabus: Elements.TaxonomyElement
	title: Elements.TextElement
	teachingadvice: Elements.LinkedItemsElement<IContentItem>
	content: Elements.RichTextElement
	contentgroups: Elements.LinkedItemsElement<IContentItem>
}>
