import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type FocusAreaSection = IContentItem<{
  focus_area_items: Elements.LinkedItemsElement<IContentItem>;
  title: Elements.TextElement;
}>;
