import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Focusareacontinuum = IContentItem<{
	stages__stage_years: Elements.TaxonomyElement
	syllabus: Elements.TaxonomyElement
	stages__stages: Elements.TaxonomyElement
	stages__stage_groups: Elements.TaxonomyElement
	title: Elements.TextElement
}>
