import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type FocusArea = IContentItem<{
  outcomes: Elements.LinkedItemsElement<IContentItem>;
  access_points: Elements.LinkedItemsElement<IContentItem>;
  title: Elements.TextElement;
  syllabustype__type: Elements.MultipleChoiceElement;
  teaching_advice: Elements.LinkedItemsElement<IContentItem>;
  focus_area_groups: Elements.LinkedItemsElement<IContentItem>;
}>;
