import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type FocusArea = IContentItem<{
  outcomes: Elements.LinkedItemsElement<IContentItem>;
  title: Elements.TextElement;
  focus_area_sections: Elements.LinkedItemsElement<IContentItem>;
}>;
