import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type FocusAreaItem = IContentItem<{
  examples: Elements.CustomElement;
  title: Elements.TextElement;
  nesa_tags__literacy_interacting: Elements.TaxonomyElement;
  nesa_tags__literacy_listening: Elements.TaxonomyElement;
  tags: Elements.LinkedItemsElement<IContentItem>;
}>;
