import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Form = IContentItem<{
  content: Elements.TextElement;
  form_id: Elements.TextElement;
  form_action: Elements.TextElement;
  fields: Elements.LinkedItemsElement<IContentItem>;
  title: Elements.TextElement;
  submit_label: Elements.TextElement;
}>;
