import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Glossary = IContentItem<{
	title: Elements.TextElement
	description: Elements.RichTextElement
	syllabus: Elements.TaxonomyElement
}>
