import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type GridColumn = IContentItem<{
	column_widths__lg: Elements.NumberElement
	tile_content: Elements.LinkedItemsElement<IContentItem>
	column_widths__md: Elements.NumberElement
	column_widths__xs: Elements.NumberElement
	column_widths__sm: Elements.NumberElement
}>
