import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type HomepageTileCallout = IContentItem<{
	divider_color: Elements.CustomElement
	font_color: Elements.CustomElement
	tiles: Elements.LinkedItemsElement<IContentItem>
	arrow_color: Elements.CustomElement
	background_color: Elements.CustomElement
	title: Elements.TextElement
}>
