import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type HomepageTileCalloutTile = IContentItem<{
	column_widths__lg: Elements.NumberElement
	title: Elements.TextElement
	column_widths__md: Elements.NumberElement
	prefix: Elements.TextElement
	column_widths__xs: Elements.NumberElement
	path: Elements.LinkedItemsElement<IContentItem>
	column_widths__sm: Elements.NumberElement
}>
