import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type HomepageBanner = IContentItem<{
	title: Elements.TextElement
	button_label: Elements.TextElement
}>
