import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Icon = IContentItem<{
  icon_position: Elements.MultipleChoiceElement;
  icon: Elements.CustomElement;
}>;
