import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type LinkCardsListSection = IContentItem<{
	cards: Elements.LinkedItemsElement<IContentItem>
	title: Elements.TextElement
}>
