import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type ListingSection = IContentItem<{
  options: Elements.MultipleChoiceElement;
  title: Elements.TextElement;
  content_type: Elements.TextElement;
  subtitle: Elements.RichTextElement;
  number_of_items: Elements.NumberElement;
  order_by: Elements.TextElement;
}>;
