import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type MathFormula = IContentItem<{
	is_block: Elements.MultipleChoiceElement
	formula: Elements.CustomElement
}>
