import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type NewsletterSubscribeBox = IContentItem<{
	createsend_action: Elements.TextElement
	createsend_id: Elements.TextElement
	input_label: Elements.TextElement
	button_label: Elements.TextElement
	title: Elements.TextElement
}>
