import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Outcome = IContentItem<{
  description: Elements.CustomElement;
  code: Elements.TextElement;
  stages: Elements.LinkedItemsElement<IContentItem>;
}>;
