import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Outcome = IContentItem<{
	description: Elements.RichTextElement
	syllabus_type__items: Elements.TaxonomyElement
	stages__stage_years: Elements.TaxonomyElement
	code: Elements.TextElement
	syllabus: Elements.TaxonomyElement
	relatedlifeskillsoutcomes: Elements.LinkedItemsElement<IContentItem>
	stages__stages: Elements.TaxonomyElement
	stages__stage_groups: Elements.TaxonomyElement
	isoverarching: Elements.MultipleChoiceElement
}>
