import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type PageGeneralContent = IContentItem<{
	title: Elements.TextElement
	summary: Elements.RichTextElement
	sections: Elements.LinkedItemsElement<IContentItem>
}>
