import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Post = IContentItem<{
  publishing_date: Elements.DateTimeElement;
  subtitle: Elements.TextElement;
  seo__description: Elements.TextElement;
  seo__options: Elements.MultipleChoiceElement;
  seo__canonical_url: Elements.TextElement;
  author: Elements.LinkedItemsElement<IContentItem>;
  excerpt: Elements.TextElement;
  seo__keywords: Elements.TextElement;
  seo__title: Elements.TextElement;
  image: Elements.AssetsElement;
  content: Elements.RichTextElement;
  slug: Elements.UrlSlugElement;
  title: Elements.TextElement;
}>;
