import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type PricingSection = IContentItem<{
  title: Elements.TextElement;
  pricing_plans: Elements.LinkedItemsElement<IContentItem>;
  metadata: Elements.MultipleChoiceElement;
  subtitle: Elements.RichTextElement;
}>;
