import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type PricingPlan = IContentItem<{
  options: Elements.MultipleChoiceElement;
  actions: Elements.LinkedItemsElement<IContentItem>;
  subtitle: Elements.TextElement;
  price: Elements.TextElement;
  details: Elements.RichTextElement;
  title: Elements.TextElement;
}>;
