import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type SelectFormField = IContentItem<{
  options: Elements.LinkedItemsElement<IContentItem>;
  label: Elements.TextElement;
  configuration: Elements.MultipleChoiceElement;
  name: Elements.TextElement;
  default_value: Elements.TextElement;
}>;
