import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type SimplePage = IContentItem<{
  subtitle: Elements.TextElement;
  image: Elements.AssetsElement;
  title: Elements.TextElement;
  content: Elements.RichTextElement;
}>;
