import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Stage = IContentItem<{
  order: Elements.NumberElement;
  title: Elements.TextElement;
  years: Elements.MultipleChoiceElement;
}>;
