import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Syllabus = IContentItem<{
  available: Elements.MultipleChoiceElement;
  key_learning_area: Elements.LinkedItemsElement<IContentItem>;
  assessments: Elements.LinkedItemsElement<IContentItem>;
  aim: Elements.CustomElement;
  overview: Elements.CustomElement;
  code: Elements.TextElement;
  stages: Elements.LinkedItemsElement<IContentItem>;
  title: Elements.TextElement;
  rich_text: Elements.RichTextElement;
  rationale: Elements.CustomElement;
  focus_areas: Elements.LinkedItemsElement<IContentItem>;
}>;
