import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Syllabus = IContentItem<{
	organisationofcontent: Elements.RichTextElement
	syllabus: Elements.TaxonomyElement
	coursenumbers: Elements.LinkedItemsElement<IContentItem>
	doredirect: Elements.MultipleChoiceElement
	web_content_rtb__content: Elements.RichTextElement
	syllabus_type__items: Elements.TaxonomyElement
	stages__stage_years: Elements.TaxonomyElement
	enrolment_type__items: Elements.TaxonomyElement
	learning_k10: Elements.RichTextElement
	introduction: Elements.RichTextElement
	from_date: Elements.DateTimeElement
	aim: Elements.RichTextElement
	rosa_hsc: Elements.LinkedItemsElement<IContentItem>
	prerequisits: Elements.LinkedItemsElement<IContentItem>
	rationale: Elements.RichTextElement
	assessments: Elements.LinkedItemsElement<IContentItem>
	learning_y11: Elements.RichTextElement
	related_life_skills_syllabus: Elements.LinkedItemsElement<IContentItem>
	learning_y12: Elements.RichTextElement
	selftuition: Elements.MultipleChoiceElement
	overview_200hourrules: Elements.RichTextElement
	outcomes: Elements.LinkedItemsElement<IContentItem>
	code: Elements.TextElement
	stages__stages: Elements.TaxonomyElement
	stages__stage_groups: Elements.TaxonomyElement
	exclusions: Elements.LinkedItemsElement<IContentItem>
	rosa_stage4_5: Elements.LinkedItemsElement<IContentItem>
	to_date: Elements.DateTimeElement
	title: Elements.TextElement
	redirecturl: Elements.TextElement
	focus_area_continum_groups: Elements.LinkedItemsElement<IContentItem>
	key_learning_area__items: Elements.TaxonomyElement
	eligibility: Elements.RichTextElement
	corequisites: Elements.LinkedItemsElement<IContentItem>
	overview100hourrules: Elements.RichTextElement
	requirements: Elements.RichTextElement
	otherinfo: Elements.RichTextElement
	focus_areas: Elements.LinkedItemsElement<IContentItem>
}>
