import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type UiCollectionSyllabus = IContentItem<{
	collection: Elements.LinkedItemsElement<IContentItem>
	tile_colour: Elements.MultipleChoiceElement
}>
