import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type UiGlobalalert = IContentItem<{
	item: Elements.LinkedItemsElement<IContentItem>
	type: Elements.MultipleChoiceElement
}>
