import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type UiHerobanner = IContentItem<{
	theme: Elements.MultipleChoiceElement
	display: Elements.MultipleChoiceElement
	items: Elements.LinkedItemsElement<IContentItem>
}>
