import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type UiInpagealert = IContentItem<{
	type: Elements.MultipleChoiceElement
	item: Elements.LinkedItemsElement<IContentItem>
	display: Elements.MultipleChoiceElement
}>
