import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type WebReleaseSyllabus = IContentItem<{
	_release_date: Elements.DateTimeElement
	_title: Elements.TextElement
	_release_notes: Elements.RichTextElement
	_version: Elements.TextElement
}>
