import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Weblinkint = IContentItem<{
	item: Elements.LinkedItemsElement<IContentItem>
	title: Elements.TextElement
	_sub_title: Elements.TextElement
}>
