import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type Weblinkext = IContentItem<{
	subtitle: Elements.TextElement
	link_url: Elements.TextElement
	title: Elements.TextElement
}>
