import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type WpGlossary = IContentItem<{
	web_content_rtb__content: Elements.RichTextElement
	seo__description: Elements.TextElement
	seo__robots: Elements.MultipleChoiceElement
	seo__canonical_url: Elements.TextElement
	slug: Elements.UrlSlugElement
	subpages: Elements.LinkedItemsElement<IContentItem>
	title: Elements.TextElement
	show_in_page_navigation: Elements.MultipleChoiceElement
	seo__keywords: Elements.TextElement
	seo__title: Elements.TextElement
	redirect_url: Elements.TextElement
}>
