import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type WpHomepage = IContentItem<{
	favicon: Elements.AssetsElement
	secondary_links: Elements.LinkedItemsElement<IContentItem>
	logo_main: Elements.AssetsElement
	web_content_rtb__content: Elements.RichTextElement
	footer_top_content: Elements.RichTextElement
	social_links: Elements.LinkedItemsElement<IContentItem>
	subpages: Elements.LinkedItemsElement<IContentItem>
	seo__description: Elements.TextElement
	seo__robots: Elements.MultipleChoiceElement
	acknowledgement: Elements.RichTextElement
	palette: Elements.MultipleChoiceElement
	seo__canonical_url: Elements.TextElement
	title: Elements.TextElement
	site_prefix: Elements.TextElement
	subtitle: Elements.TextElement
	main_menu: Elements.LinkedItemsElement<IContentItem>
	seo__keywords: Elements.TextElement
	seo__title: Elements.TextElement
	copyright_link: Elements.LinkedItemsElement<IContentItem>
	footer_menu_links: Elements.LinkedItemsElement<IContentItem>
	descriptor: Elements.TextElement
}>
