import { IContentItem, Elements } from '@kentico/kontent-delivery'

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type WpResources = IContentItem<{
	web_content_rtb__content: Elements.RichTextElement
	seo__description: Elements.TextElement
	seo__robots: Elements.MultipleChoiceElement
	seo__canonical_url: Elements.TextElement
	redirect_url: Elements.TextElement
	seo__keywords: Elements.TextElement
	title: Elements.TextElement
	seo__title: Elements.TextElement
	show_in_page_navigation: Elements.MultipleChoiceElement
	slug: Elements.UrlSlugElement
}>
